### ISSUE TITLE
2.0.4 fails with AttributeError: 'Namespace' object has no attribute 'extend_select'

### ISSUE THREAD

**Issue by kurtschelfthout** [snok/flake8-type-checking#108]
Thanks for fixing the bug in 2.0.3 so quickly.

Unfortunately in 2.0.4 I can't run flake8-type-checking at all anymore.

I changed flake8 config according to the readme I think - hopefully I've not misunderstood something.
```
# for flake8-type-checking
enable-extensions = TC, TC1
```
Anyway that used to work with 2.0.3.

Full error:
```
$ flake8 .
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.9/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/home/kurts/.cache/pypoetry/virtualenvs/meadowrun-bhfjFnmF-py3.9/lib/python3.9/site-packages/flake8/checker.py", line 676, in _run_checks
    return checker.run_checks()
  File "/home/kurts/.cache/pypoetry/virtualenvs/meadowrun-bhfjFnmF-py3.9/lib/python3.9/site-packages/flake8_noqa/noqa_filter.py", line 185, in run_checks
    result = super().run_checks(*args, **kwargs)
  File "/home/kurts/.cache/pypoetry/virtualenvs/meadowrun-bhfjFnmF-py3.9/lib/python3.9/site-packages/flake8/checker.py", line 589, in run_checks
    self.run_ast_checks()
  File "/home/kurts/.cache/pypoetry/virtualenvs/meadowrun-bhfjFnmF-py3.9/lib/python3.9/site-packages/flake8/checker.py", line 494, in run_ast_checks
    for (line_number, offset, text, _) in runner:
  File "/home/kurts/.cache/pypoetry/virtualenvs/meadowrun-bhfjFnmF-py3.9/lib/python3.9/site-packages/flake8_type_checking/plugin.py", line 88, in run
    if self.should_warn(e[2].split(':')[0]):
  File "/home/kurts/.cache/pypoetry/virtualenvs/meadowrun-bhfjFnmF-py3.9/lib/python3.9/site-packages/flake8_type_checking/plugin.py", line 120, in should_warn
    + list(self.options.extend_select or [])
AttributeError: 'Namespace' object has no attribute 'extend_select'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/kurts/.cache/pypoetry/virtualenvs/meadowrun-bhfjFnmF-py3.9/bin/flake8", line 8, in <module>
    sys.exit(main())
  File "/home/kurts/.cache/pypoetry/virtualenvs/meadowrun-bhfjFnmF-py3.9/lib/python3.9/site-packages/flake8/main/cli.py", line 22, in main
    app.run(argv)
  File "/home/kurts/.cache/pypoetry/virtualenvs/meadowrun-bhfjFnmF-py3.9/lib/python3.9/site-packages/flake8/main/application.py", line 363, in run
    self._run(argv)
  File "/home/kurts/.cache/pypoetry/virtualenvs/meadowrun-bhfjFnmF-py3.9/lib/python3.9/site-packages/flake8/main/application.py", line 351, in _run
    self.run_checks()
  File "/home/kurts/.cache/pypoetry/virtualenvs/meadowrun-bhfjFnmF-py3.9/lib/python3.9/site-packages/flake8/main/application.py", line 264, in run_checks
    self.file_checker_manager.run()
  File "/home/kurts/.cache/pypoetry/virtualenvs/meadowrun-bhfjFnmF-py3.9/lib/python3.9/site-packages/flake8/checker.py", line 321, in run
    self.run_parallel()
  File "/home/kurts/.cache/pypoetry/virtualenvs/meadowrun-bhfjFnmF-py3.9/lib/python3.9/site-packages/flake8/checker.py", line 287, in run_parallel
    for ret in pool_map:
  File "/usr/lib/python3.9/multiprocessing/pool.py", line 448, in <genexpr>
    return (item for chunk in result for item in chunk)
  File "/usr/lib/python3.9/multiprocessing/pool.py", line 870, in next
    raise value
AttributeError: 'Namespace' object has no attribute 'extend_select'
```

**Comment by JonasKs** [comment]
Related? https://github.com/PyCQA/flake8/issues/1318

Which Flake8 version are you on?

**Comment by kurtschelfthout** [comment]
Ah possibly:

```
$ flake8 --version
3.9.2 (flake8-noqa: 1.2.5, flake8-type-checking: 2.0.4, flake8_encodings: 0.5.0.post1, mccabe: 0.6.1, pycodestyle: 2.7.0, pyflakes: 2.3.1) CPython 3.9.13 on Linux
```

We pinned to 3.9.2 because of this whole flake/importlib drama, honestly I haven't been following it.

**Comment by sondrelg** [comment]
I'll see if I can fix this and release a new version later today @kurtschelfthout. Thanks for letting me know 👍

**Comment by sondrelg** [comment]
v2.0.5 should be out in a minute @kurtschelfthout. Would you mind letting me know if that solves your problem? 🙂

**Comment by kurtschelfthout** [comment]
Yes it does, thanks again for the quick fix.
